### ISSUE TITLE
Does not open the sample app

### ISSUE THREAD

**Issue by jsaiti** [sdkdimon/kms-ios-client#1]
dyld: Library not loaded: @rpath/SocketRocket.framework/SocketRocket
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/KMSClient-bvfsoyeemgolpkfilysgxdhawepj/Build/Products/Debug-iphonesimulator/KMSClient.framework/KMSClient
  Reason: image not found

**Comment by sdkdimon** [comment]
Seems to be you open LoopBackCall.xcodeproj instead you should open KMSClient.xcworkspace and select LoopBackCall target.

**Comment by jsaiti** [comment]
When I open  LoopBackCall.xcodeproj, does not know the libraries (ReactiveObjC, SocketRocked, etc) and when it opens   KMSClient.xcworkspace  and select LoopBackCall, the app builded successfully, but when it tends to open in the device, crashes with that error I have presented above.

**Comment by sdkdimon** [comment]
You must delete from Embedded Binaries section KMSClient.framework and add it again, at LoopBackCall target general tab, it's Xcode issue, i will fix it with next commit .

**Comment by jsaiti** [comment]
I fixed this by was copy SocketRocket.framework from DerivedData and added manually on the project and on the Embedded Binaries.

Thanks a lot
Jusuf Saiti
